 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/atividades", type: :request do
  # Atividade. As you add validations to Atividade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Atividade.create! valid_attributes
      get atividades_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      atividade = Atividade.create! valid_attributes
      get atividade_url(atividade)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_atividade_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      atividade = Atividade.create! valid_attributes
      get edit_atividade_url(atividade)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Atividade" do
        expect {
          post atividades_url, params: { atividade: valid_attributes }
        }.to change(Atividade, :count).by(1)
      end

      it "redirects to the created atividade" do
        post atividades_url, params: { atividade: valid_attributes }
        expect(response).to redirect_to(atividade_url(Atividade.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Atividade" do
        expect {
          post atividades_url, params: { atividade: invalid_attributes }
        }.to change(Atividade, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post atividades_url, params: { atividade: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested atividade" do
        atividade = Atividade.create! valid_attributes
        patch atividade_url(atividade), params: { atividade: new_attributes }
        atividade.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the atividade" do
        atividade = Atividade.create! valid_attributes
        patch atividade_url(atividade), params: { atividade: new_attributes }
        atividade.reload
        expect(response).to redirect_to(atividade_url(atividade))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        atividade = Atividade.create! valid_attributes
        patch atividade_url(atividade), params: { atividade: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested atividade" do
      atividade = Atividade.create! valid_attributes
      expect {
        delete atividade_url(atividade)
      }.to change(Atividade, :count).by(-1)
    end

    it "redirects to the atividades list" do
      atividade = Atividade.create! valid_attributes
      delete atividade_url(atividade)
      expect(response).to redirect_to(atividades_url)
    end
  end
end
