 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contactos", type: :request do
  # Contacto. As you add validations to Contacto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Contacto.create! valid_attributes
      get contactos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contacto = Contacto.create! valid_attributes
      get contacto_url(contacto)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contacto_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      contacto = Contacto.create! valid_attributes
      get edit_contacto_url(contacto)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contacto" do
        expect {
          post contactos_url, params: { contacto: valid_attributes }
        }.to change(Contacto, :count).by(1)
      end

      it "redirects to the created contacto" do
        post contactos_url, params: { contacto: valid_attributes }
        expect(response).to redirect_to(contacto_url(Contacto.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contacto" do
        expect {
          post contactos_url, params: { contacto: invalid_attributes }
        }.to change(Contacto, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contactos_url, params: { contacto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contacto" do
        contacto = Contacto.create! valid_attributes
        patch contacto_url(contacto), params: { contacto: new_attributes }
        contacto.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contacto" do
        contacto = Contacto.create! valid_attributes
        patch contacto_url(contacto), params: { contacto: new_attributes }
        contacto.reload
        expect(response).to redirect_to(contacto_url(contacto))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        contacto = Contacto.create! valid_attributes
        patch contacto_url(contacto), params: { contacto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contacto" do
      contacto = Contacto.create! valid_attributes
      expect {
        delete contacto_url(contacto)
      }.to change(Contacto, :count).by(-1)
    end

    it "redirects to the contactos list" do
      contacto = Contacto.create! valid_attributes
      delete contacto_url(contacto)
      expect(response).to redirect_to(contactos_url)
    end
  end
end
