 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/entregaemcasas", type: :request do
  # Entregaemcasa. As you add validations to Entregaemcasa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Entregaemcasa.create! valid_attributes
      get entregaemcasas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      entregaemcasa = Entregaemcasa.create! valid_attributes
      get entregaemcasa_url(entregaemcasa)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_entregaemcasa_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      entregaemcasa = Entregaemcasa.create! valid_attributes
      get edit_entregaemcasa_url(entregaemcasa)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Entregaemcasa" do
        expect {
          post entregaemcasas_url, params: { entregaemcasa: valid_attributes }
        }.to change(Entregaemcasa, :count).by(1)
      end

      it "redirects to the created entregaemcasa" do
        post entregaemcasas_url, params: { entregaemcasa: valid_attributes }
        expect(response).to redirect_to(entregaemcasa_url(Entregaemcasa.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Entregaemcasa" do
        expect {
          post entregaemcasas_url, params: { entregaemcasa: invalid_attributes }
        }.to change(Entregaemcasa, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post entregaemcasas_url, params: { entregaemcasa: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested entregaemcasa" do
        entregaemcasa = Entregaemcasa.create! valid_attributes
        patch entregaemcasa_url(entregaemcasa), params: { entregaemcasa: new_attributes }
        entregaemcasa.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the entregaemcasa" do
        entregaemcasa = Entregaemcasa.create! valid_attributes
        patch entregaemcasa_url(entregaemcasa), params: { entregaemcasa: new_attributes }
        entregaemcasa.reload
        expect(response).to redirect_to(entregaemcasa_url(entregaemcasa))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        entregaemcasa = Entregaemcasa.create! valid_attributes
        patch entregaemcasa_url(entregaemcasa), params: { entregaemcasa: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested entregaemcasa" do
      entregaemcasa = Entregaemcasa.create! valid_attributes
      expect {
        delete entregaemcasa_url(entregaemcasa)
      }.to change(Entregaemcasa, :count).by(-1)
    end

    it "redirects to the entregaemcasas list" do
      entregaemcasa = Entregaemcasa.create! valid_attributes
      delete entregaemcasa_url(entregaemcasa)
      expect(response).to redirect_to(entregaemcasas_url)
    end
  end
end
