 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/menudegustacaos", type: :request do
  # Menudegustacao. As you add validations to Menudegustacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Menudegustacao.create! valid_attributes
      get menudegustacaos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      menudegustacao = Menudegustacao.create! valid_attributes
      get menudegustacao_url(menudegustacao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_menudegustacao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      menudegustacao = Menudegustacao.create! valid_attributes
      get edit_menudegustacao_url(menudegustacao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Menudegustacao" do
        expect {
          post menudegustacaos_url, params: { menudegustacao: valid_attributes }
        }.to change(Menudegustacao, :count).by(1)
      end

      it "redirects to the created menudegustacao" do
        post menudegustacaos_url, params: { menudegustacao: valid_attributes }
        expect(response).to redirect_to(menudegustacao_url(Menudegustacao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Menudegustacao" do
        expect {
          post menudegustacaos_url, params: { menudegustacao: invalid_attributes }
        }.to change(Menudegustacao, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post menudegustacaos_url, params: { menudegustacao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested menudegustacao" do
        menudegustacao = Menudegustacao.create! valid_attributes
        patch menudegustacao_url(menudegustacao), params: { menudegustacao: new_attributes }
        menudegustacao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the menudegustacao" do
        menudegustacao = Menudegustacao.create! valid_attributes
        patch menudegustacao_url(menudegustacao), params: { menudegustacao: new_attributes }
        menudegustacao.reload
        expect(response).to redirect_to(menudegustacao_url(menudegustacao))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        menudegustacao = Menudegustacao.create! valid_attributes
        patch menudegustacao_url(menudegustacao), params: { menudegustacao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested menudegustacao" do
      menudegustacao = Menudegustacao.create! valid_attributes
      expect {
        delete menudegustacao_url(menudegustacao)
      }.to change(Menudegustacao, :count).by(-1)
    end

    it "redirects to the menudegustacaos list" do
      menudegustacao = Menudegustacao.create! valid_attributes
      delete menudegustacao_url(menudegustacao)
      expect(response).to redirect_to(menudegustacaos_url)
    end
  end
end
