Produto.create(:nome => 'Quinta da Terrincha', :descricao=>'Doc Douro Tinto',:ano=>'2013', :preco=>'7', :imagem=>'1-tinto.png')
Produto.create(:nome => 'Terrincha', :descricao=>'DOC Douro Branco',:ano=>'2018', :preco=>'7', :imagem=>'2-branco.png')
Produto.create(:nome => 'Terrincha', :descricao=>'DOC Douro Rosé',:ano=>'2018', :preco=>'6', :imagem=>'3-rose.png')
Produto.create(:nome => 'Terras da Vilariça', :descricao=>'DOC Douro Tinto',:ano=>'2015', :preco=>'6', :imagem=>'4-vilarica.png')
Produto.create(:nome => 'Terrincha Reserva', :descricao=>'DOC Douro Tinto',:ano=>'2016', :preco=>'12', :imagem=>'5-tinto.png')
Produto.create(:nome => 'Quinta da Terrincha', :descricao=>'DOC Douro Branco',:ano=>'LT-15 2015', :preco=>'15', :imagem=>'6-diamante.png')
Produto.create(:nome => 'Terrincha', :descricao=>'DOC Douro Branco',:ano=>'B-16 2016', :preco=>'15', :imagem=>'7-diamante.png')
Produto.create(:nome => 'Terrincha Reserva', :descricao=>'DOC Douro Branco',:ano=>'2015', :preco=>'25', :imagem=>'8-reserva.png')

Casa.create(:nome => 'Casa do Jardineiro')
Casa.create(:nome => 'Casa da Criada')
Casa.create(:nome => 'Casa do Azeiteiro')
Casa.create(:nome => 'Casa do Ceifeiro')
Casa.create(:nome => 'Casa do Podador')
Casa.create(:nome => 'Casa Do Caseiro')
Casa.create(:nome => 'Casa do Guarda')
Casa.create(:nome => 'Casa do Pastor')
Casa.create(:nome => 'Casa da Palha')
Casa.create(:nome => 'Casa dos Bois')
Casa.create(:nome => 'Casa do Enxertador')
Casa.create(:nome => 'Casa da Eira')
Casa.create(:nome => 'Casa da Francela')
Casa.create(:nome => 'Casa da Lenha')
Casa.create(:nome => 'Casa dos Cavalos')
Casa.create(:nome => 'Casa Mãe')
